name: dev build to s3
on:
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
    steps:
      - uses: actions/checkout@main
      - run: echo mapbox token $MAPBOX_TOKEN
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn generate-dev
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'dist'
          destination_dir: ''
